apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
    tier: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000 
      targetPort: 3000 
